#ifndef _ONENET_PORT_CONFIG_H_
#define _ONENET_PORT_CONFIG_H_

#include <rtconfig.h>

#ifdef BSP_USING_ONENET

#define PKG_USING_ONENET

#ifdef BSP_ONENET_USING_SAMPLE
#define PKG_USING_ONENET_SAMPLE
#endif

#ifdef BSP_ONENET_USING_MQTT
#define ONENET_USING_MQTT
#endif

#ifdef BSP_ONENET_USING_HTTP
#define ONENET_USING_HTTP
#endif

#ifdef BSP_ONENET_USING_AUTO_REGISTER
#define ONENET_USING_AUTO_REGISTER
#endif

#ifdef BSP_ONENET_REGISTRATION_CODE
#define ONENET_REGISTRATION_CODE BSP_ONENET_REGISTRATION_CODE
#endif

#ifdef BSP_ONENET_INFO_DEVID
#define ONENET_INFO_DEVID BSP_ONENET_INFO_DEVID
#endif


#include "../../onenet_auth_info.h"
#define ONENET_INFO_AUTH ONENET_AUTH_INFO_STRING


#ifdef BSP_ONENET_INFO_PROID
#define ONENET_INFO_PROID BSP_ONENET_INFO_PROID
#endif

#ifdef BSP_ONENET_AUTO_REPLY_SET
#define ONENET_AUTO_REPLY_SET
#endif

#ifdef BSP_ONENET_AUTO_REPLY_GET
#define ONENET_AUTO_REPLY_GET
#endif

#ifdef BSP_ONENET_AUTO_REPLY_OTA
#define ONENET_AUTO_REPLY_OTA
#endif

#endif

#endif
